import type { Student, Application, Task, Notification, User } from "@meridian/types";

export const currentUser: User = {
  id: "u1",
  name: "Sarah Chen",
  email: "sarah@meridian.edu",
  role: "Senior Counselor",
  initials: "SC",
  avatarColor: "#2563eb",
};

export const students: Student[] = [
  {
    id: "s1",
    name: "Ahmed Al-Rashidi",
    email: "ahmed@email.com",
    phone: "+880 1711 234567",
    nationality: "Bangladeshi",
    dateOfBirth: "1999-03-15",
    passportNumber: "BN1234567",
    preferredCountry: "United Kingdom",
    intake: "Sep 2026",
    degreeLevel: "Master",
    status: "active",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 7.0,
    gpa: "3.6",
    university: "University of Manchester",
    createdAt: "2025-12-01",
    updatedAt: "2026-06-28",
  },
  {
    id: "s2",
    name: "Fatima Noor",
    email: "fatima@email.com",
    phone: "+880 1812 345678",
    nationality: "Bangladeshi",
    dateOfBirth: "2000-07-22",
    passportNumber: "BN2345678",
    preferredCountry: "Canada",
    intake: "Jan 2027",
    degreeLevel: "Master",
    status: "active",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 6.5,
    gpa: "3.8",
    university: "University of Toronto",
    createdAt: "2026-01-10",
    updatedAt: "2026-07-01",
  },
  {
    id: "s3",
    name: "Rahul Sharma",
    email: "rahul@email.com",
    phone: "+91 9876 543210",
    nationality: "Indian",
    dateOfBirth: "2001-11-08",
    passportNumber: "IN3456789",
    preferredCountry: "Australia",
    intake: "Feb 2027",
    degreeLevel: "Bachelor",
    status: "lead",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: null,
    gpa: "3.2",
    university: "",
    createdAt: "2026-05-20",
    updatedAt: "2026-06-30",
  },
  {
    id: "s4",
    name: "Priya Patel",
    email: "priya@email.com",
    phone: "+91 9123 456789",
    nationality: "Indian",
    dateOfBirth: "1998-04-12",
    passportNumber: "IN4567890",
    preferredCountry: "United Kingdom",
    intake: "Sep 2026",
    degreeLevel: "PhD",
    status: "enrolled",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 7.5,
    gpa: "3.9",
    university: "Imperial College London",
    createdAt: "2025-08-15",
    updatedAt: "2026-06-25",
  },
  {
    id: "s5",
    name: "Mohammad Hasan",
    email: "hasan@email.com",
    phone: "+880 1911 567890",
    nationality: "Bangladeshi",
    dateOfBirth: "2000-01-30",
    passportNumber: "BN5678901",
    preferredCountry: "United States",
    intake: "Fall 2026",
    degreeLevel: "Master",
    status: "active",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 6.0,
    gpa: "3.4",
    university: "",
    createdAt: "2026-03-01",
    updatedAt: "2026-07-02",
  },
  {
    id: "s6",
    name: "Tasnim Akter",
    email: "tasnim@email.com",
    phone: "+880 1611 678901",
    nationality: "Bangladeshi",
    dateOfBirth: "2001-09-05",
    passportNumber: "BN6789012",
    preferredCountry: "Canada",
    intake: "Sep 2026",
    degreeLevel: "Bachelor",
    status: "inactive",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 5.5,
    gpa: "3.0",
    university: "",
    createdAt: "2026-02-14",
    updatedAt: "2026-04-10",
  },
  {
    id: "s7",
    name: "Arjun Mehta",
    email: "arjun@email.com",
    phone: "+91 9234 567890",
    nationality: "Indian",
    dateOfBirth: "1999-12-20",
    passportNumber: "IN7890123",
    preferredCountry: "Germany",
    intake: "Oct 2026",
    degreeLevel: "Master",
    status: "active",
    counselorId: "u1",
    counselorName: "Sarah Chen",
    ieltsOverall: 7.0,
    gpa: "3.7",
    university: "TU Munich",
    createdAt: "2026-01-05",
    updatedAt: "2026-07-03",
  },
];

export const applications: Application[] = [
  {
    id: "a1",
    studentId: "s1",
    studentName: "Ahmed Al-Rashidi",
    universityId: "uni1",
    universityName: "University of Manchester",
    courseName: "MSc Data Science",
    country: "United Kingdom",
    intake: "Sep 2026",
    stage: "conditional-offer",
    priority: "high",
    progress: 75,
    missingDocs: 1,
    createdAt: "2026-01-15",
    updatedAt: "2026-07-01",
  },
  {
    id: "a2",
    studentId: "s2",
    studentName: "Fatima Noor",
    universityId: "uni2",
    universityName: "University of Toronto",
    courseName: "MA Economics",
    country: "Canada",
    intake: "Jan 2027",
    stage: "documents",
    priority: "medium",
    progress: 30,
    missingDocs: 3,
    createdAt: "2026-03-20",
    updatedAt: "2026-07-02",
  },
  {
    id: "a3",
    studentId: "s4",
    studentName: "Priya Patel",
    universityId: "uni3",
    universityName: "Imperial College London",
    courseName: "PhD Computer Science",
    country: "United Kingdom",
    intake: "Sep 2026",
    stage: "enrolled",
    priority: "high",
    progress: 100,
    missingDocs: 0,
    createdAt: "2025-10-01",
    updatedAt: "2026-06-20",
  },
  {
    id: "a4",
    studentId: "s5",
    studentName: "Mohammad Hasan",
    universityId: "uni4",
    universityName: "MIT",
    courseName: "MS Computer Science",
    country: "United States",
    intake: "Fall 2026",
    stage: "submitted",
    priority: "high",
    progress: 50,
    missingDocs: 0,
    createdAt: "2026-04-10",
    updatedAt: "2026-06-28",
  },
  {
    id: "a5",
    studentId: "s1",
    studentName: "Ahmed Al-Rashidi",
    universityId: "uni5",
    universityName: "University of Leeds",
    courseName: "MSc AI",
    country: "United Kingdom",
    intake: "Sep 2026",
    stage: "under-review",
    priority: "medium",
    progress: 60,
    missingDocs: 0,
    createdAt: "2026-02-01",
    updatedAt: "2026-07-03",
  },
  {
    id: "a6",
    studentId: "s7",
    studentName: "Arjun Mehta",
    universityId: "uni6",
    universityName: "TU Munich",
    courseName: "MSc Mechanical Engineering",
    country: "Germany",
    intake: "Oct 2026",
    stage: "lead",
    priority: "low",
    progress: 10,
    missingDocs: 4,
    createdAt: "2026-06-15",
    updatedAt: "2026-07-01",
  },
  {
    id: "a7",
    studentId: "s2",
    studentName: "Fatima Noor",
    universityId: "uni7",
    universityName: "McGill University",
    courseName: "MA International Relations",
    country: "Canada",
    intake: "Jan 2027",
    stage: "rejected",
    priority: "medium",
    progress: 100,
    missingDocs: 0,
    createdAt: "2026-02-20",
    updatedAt: "2026-06-15",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Follow up Ahmed's IELTS score",
    priority: "high",
    status: "todo",
    dueDate: "2026-07-07",
    assigneeId: "u1",
    assigneeName: "Sarah Chen",
  },
  {
    id: "t2",
    title: "Collect Fatima's transcripts",
    priority: "high",
    status: "in-progress",
    dueDate: "2026-07-08",
    assigneeId: "u1",
    assigneeName: "Sarah Chen",
  },
  {
    id: "t3",
    title: "Submit Arjun's TU Munich application",
    priority: "medium",
    status: "todo",
    dueDate: "2026-07-10",
    assigneeId: "u1",
    assigneeName: "Sarah Chen",
  },
  {
    id: "t4",
    title: "Review Mohammad's SOP draft",
    priority: "medium",
    status: "todo",
    dueDate: "2026-07-12",
    assigneeId: "u1",
    assigneeName: "Sarah Chen",
  },
  {
    id: "t5",
    title: "Schedule call with Rahul's parents",
    priority: "low",
    status: "done",
    dueDate: "2026-07-05",
    assigneeId: "u1",
    assigneeName: "Sarah Chen",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "success",
    title: "Offer received",
    message: "Ahmed received conditional offer from University of Manchester",
    read: false,
    createdAt: "2026-07-03T10:30:00Z",
  },
  {
    id: "n2",
    type: "warning",
    title: "Deadline approaching",
    message: "Fatima's transcript submission due in 3 days",
    read: false,
    createdAt: "2026-07-03T09:15:00Z",
  },
  {
    id: "n3",
    type: "info",
    title: "Application update",
    message: "Mohammad's MIT application moved to review stage",
    read: true,
    createdAt: "2026-07-02T16:45:00Z",
  },
  {
    id: "n4",
    type: "message",
    title: "New message",
    message: "Rahul sent a message regarding visa documents",
    read: false,
    createdAt: "2026-07-02T14:20:00Z",
  },
];

export const dashboardStats = {
  totalStudents: 142,
  activeApplications: 89,
  offersReceived: 34,
  enrolledThisYear: 28,
  pendingTasks: 12,
  conversionRate: 76,
};
